[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3.11 -m pip install --upgrade pip",
  "python3.11 -m pip install --no-cache-dir --force-reinstall -r requirements-clean.txt"
]

[start]
cmd = "python3.11 main.py"

[variables]
PYTHON_VERSION = "3.11"
